FROM python:3.8-slim

WORKDIR /app

COPY . /app

RUN pip install flask

EXPOSE 5000

CMD ["python", "app.py"]

#########################################################
Сборка: docker build -t my-flask-app .
Запуск: docker run -p 5000:5000 my-flask-app
#########################################################